### ISSUE TITLE
Remove last queued track

### ISSUE THREAD

**Issue by jscharpff** [osteenbergen/slackify#4]
Pop the last queued track from the queue using for instance '@spotify remove last'. Maybe even with negative indexes, e.g. @spotify: r -1 to allow removing traks from the other end of the queues

**Comment by osteenbergen** [comment]
Remove last can be done, negative numbers will not be implemented as this version uses unique numbers for queueing (so just use `@slackify: remove 1289`).

**Comment by osteenbergen** [comment]
Marking as closed as `@slackify remove last` has been implemented
