### ISSUE TITLE
Audio keeps interrupting

### ISSUE THREAD

**Issue by Thesulac** [osteenbergen/slackify#6]
When playing audio through Slackify it keeps interrupting. It is not always the same time between the interrupts, sometimes it's 10 seconds, sometimes its a minute.

This happens on both Mac and on a Raspberry Pi. When using the standard Spotify client, it does work flawlessly. On Raspberry Pi it uses the ALSA audio, on Mac it uses the PortAudio Sink.

**Comment by osteenbergen** [comment]
Probably the pyspotify library: mopidy/pyspotify#132

**Comment by osteenbergen** [comment]
Can you provide a debug log? Increase the loglevel in `slackify.py`

**Comment by Thesulac** [comment]
<script src="https://gist.github.com/Thesulac/c7588b67de36ceb750c6.js"></script>

**Comment by Thesulac** [comment]
https://gist.github.com/Thesulac/c7588b67de36ceb750c6

**Comment by osteenbergen** [comment]
Closing as its not an issue of this codebase
